default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: tvbh_development

test:
  <<: *default
  database: tvbh_test

production:
  primary:
    <<: *default
  cable:
    <<: *default